### ISSUE TITLE
DB Time UTC 설정 확인하기 (현재보다 9시간 전으로 나옴) 

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/deal-8#112]
## 요구사항
DB Time UTC 설정 확인하기 (현재보다 9시간 전으로 나옴)

**Comment by SecretJuJu** [comment]
<img width="956" alt="스크린샷 2021-07-22 오전 11 24 59" src="https://user-images.githubusercontent.com/47034129/126582325-7918b43d-0147-4516-a234-a2123dc83eda.png">
