### ISSUE TITLE
[MarkUp] Normalize 코드 수정사항

### ISSUE THREAD

**Issue by SecretJuJu** [woowa-techcamp-2021/deal-8#38]
## 개요

- [x] css 테스트 과정중 사용한 body의 border를 삭제
- [x] body의 padding 제거
- [x] body를 가운데로

**Comment by peanut-lover** [comment]
@SecretJuJu  요거 해결 된거면 Close 해도 될가요?

body vertical 이 center로 됐으려나요

**Comment by SecretJuJu** [comment]
아 네네 제가 close 하겠습니다 ㅎ
