### ISSUE TITLE
[Deploy] 자동 배포 스크립트

### ISSUE THREAD

**Issue by SecretJuJu** [woowa-techcamp-2021/deal-8#60]
## 요구사항
- 자동으로 번들을 만들어 백엔드에 업로드하는 쉘스크립트를 만든다.

## 개발방법
- 번들을 만드는 스크립트 하나, backend로 이동후 서버를 재시작하는 스크립트 하나
- 이렇게 두개를 만든다.

**Comment by peanut-lover** [comment]
제가 두개 스크립트 한번에 실행하는 것도 만들게요

**Comment by peanut-lover** [comment]
아주 간단한 스크립트만으로 충분하기 때문에 해당 이슈는 닫겟습니다.
